.TH cmarkdown 1 cmarkdown\-VERSION
.SH NAME
cmarkdown \- Markdown interpreter in C
.SH SYNOPSIS
.B cmarkdown
.RB [ \-h ]
.RB [ \-v ]
.RB [ \-n ]
.RB [ file ]
.SH DESCRIPTION
cmarkdown is a simple interpreter for the markdown syntax.
.SH OPTIONS
.TP
.B \-v
prints version information to standard error, then exits.
.TP
.B \-h
prints usage information to standard error, then exits.
.TP
.B \-n
escapes all HTML Tags.
.SH BUGS
Markdown may never be fully supported.
links on images may not work, e.g.

  [![pic](pic.png)](http://somehost)
