.TH cmarkdown 1 cmarkdown\-VERSION
.SH NAME
cmarkdown \- Markdown interpreter in C
.SH SYNOPSIS
.B cmarkdown
.RB [ \-v ]
.SH DESCRIPTION
cmarkdown is a simple interpreter for the markdown syntax.
.SH OPTIONS
.TP
.B \-v
prints version information to standard error, then exits.
.TP
.B \-h
prints usage information to standard error, then exits.
.TP
.B \-n
escape all html Tags.
.SH BUGS
Markdown may never be fully supported.
