.TH smu 1 smu\-VERSION
.SH NAME
smu \- simple markup
.SH SYNOPSIS
.B smu
.RB [ \-h ]
.RB [ \-v ]
.RB [ \-n ]
.RB [ file ]
.SH DESCRIPTION
smu is a simple interpreter for a simplified markdown dialect.
.SH OPTIONS
.TP
.B \-v
prints version information to standard error, then exits.
.TP
.B \-h
prints usage information to standard error, then exits.
.TP
.B \-n
escapes all HTML Tags.
.SH BUGS
Please report any Bugs to https://github.com/Gottox/smu/issues or via mail.
